title: teorihandboken
remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "teorihandboken on GitHub":
    - "//github.com/stenwall/teorihandboken"

# Custom color theme
color_scheme: colors-test